# You can use the variables $GPU_ID and $PROMPT in the scripts
GradeADreamer:
  - env: GradeADreamer
    scripts:
      - ./third_party/GradeADreamer/run.sh --gpu $GPU_ID --prompt $PROMPT
      - python extractors/mesh_extractor.py --prompt $PROMPT --module GradeADreamer --model GradeADreamer
ProlificDreamer:
  - env: th_studio
    scripts:
      - cd third_party/threestudio
      - python ../../trainers/threestudio.py --prompt $PROMPT --gpu $GPU_ID --model ProlificDreamer
      - cd -
      - python extractors/mesh_extractor.py --prompt $PROMPT --module threestudio --model prolificdreamer
Magic3D:
  - env: th_studio
    scripts:
      - cd third_party/threestudio
      - python ../../trainers/threestudio.py --prompt $PROMPT --gpu $GPU_ID --model Magic3D
      - cd -
      - python extractors/mesh_extractor.py --prompt $PROMPT --module threestudio --model magic3d
Fantasia3D:
  - env: th_studio
    scripts:
      - cd third_party/threestudio
      - python ../../trainers/threestudio.py --prompt $PROMPT --gpu $GPU_ID --model Fantasia3D
      - cd -
      - python extractors/mesh_extractor.py --prompt $PROMPT --module threestudio --model fantasia3d
DreamFusion:
  - env: th_studio
    scripts:
      - cd third_party/threestudio
      - python ../../trainers/threestudio.py --prompt $PROMPT --gpu $GPU_ID --model DreamFusion
      - cd -
      - python extractors/mesh_extractor.py --prompt $PROMPT --module threestudio --model dreamfusion
PlacidDreamer:
  - env: PlacidDreamer_functioning
    scripts:
      - cd third_party/PlacidDreamer
      - python ../../trainers/placiddreamer.py --prompt $PROMPT --gpu $GPU_ID --stage 1
      - conda activate PlacidDreamer3
      - python ../../trainers/placiddreamer.py --prompt $PROMPT --gpu $GPU_ID --stage 2
      - conda deactivate
      - python ../../trainers/placiddreamer.py --prompt $PROMPT --gpu $GPU_ID --stage 3
      - cd -
PlacidDreamer_meshexport:
  - env: GradeADreamer
    scripts:
      - python extractors/mesh_extractor.py --prompt $PROMPT --module placiddreamer
